var width = 10;
var height = 5;
var area = width * height;
var bill = 7;
var payment = 100;
var change = bill - payment;
var quizzes = 50;
var midterm = 100;
var final = 0;
var grade = (quizzes + midterm + final) / 3;
var firstName = 'Cynthia';
var lastName = 'Huynh';
var fullName = `${firstName} ${lastName}`;
var pH = 7;
var isAcidic = pH < 7;
var headCount = 300;
var isSparta = headCount === 300;
var motto = fullName;
motto += ' is the GOAT';

console.log('area:', area);
console.log('type area:', typeof area);
console.log('change:', change);
console.log('type change:', typeof change);
console.log('grade:', grade);
console.log('type grade:', typeof grade);
console.log('fullName:', fullName);
console.log('type full Name:', typeof fullName);
console.log('isAcidic:', isAcidic);
console.log('type is Acidic:', typeof isAcidic);
console.log('isSparta:', isSparta);
console.log('type is Sparta:', typeof isSparta);
console.log('motto:', motto);
console.log('type is motto:', typeof motto);
